app.eureka-server: eureka-server

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.web: DEBUG

---
spring.config.activate.on-profile: docker
app.eureka-server: eureka-server
spring.cloud.config.uri: http://config-server:8888