spring.application.name: edge-server

server.port: 8099

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-store-password: password
  key-alias: localhost

jwt:
  secret: mi-super-clave-jwt-muy-segura-12345678
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mi-super-clave-jwt-muy-segura-12345678
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:

        - id: puntos-service
          uri: lb://puntos-service
          predicates:
            - Path=/puntos-service/**
          filters:
            - StripPrefix=1


# Configuraci贸n para exponer endpoints de administraci贸n
management.endpoint.gateway.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

# Configuraci贸n de logging para ayudar en la depuraci贸n
logging:
  level:
    root: INFO
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO
    '[org.springframework.cloud.gateway]': TRACE
    '[org.springframework.security]': DEBUG