spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: puntos-service
          uri: lb://puntos-service
          predicates:
            - Path=/api/puntos-interes/**
          filters:
            - StripPrefix=2
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/** 
          filters:
            - StripPrefix=2 

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gis-lapaz

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE
