spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/gis
    username: postgres
    password: 133133
  application:
    name: puntosint-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gis-lapaz
          jwk-set-uri: http://keycloak:8080/realms/gis-lapaz/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
